# Generated by Django 3.1 on 2020-09-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneDataModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('d_id', models.CharField(max_length=100)),
                ('img_path', models.CharField(max_length=200)),
                ('img_name', models.DateTimeField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
