# Generated by Django 3.1 on 2020-09-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronedatamodels',
            name='img_name',
            field=models.CharField(max_length=200),
        ),
    ]
